import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from '../context/CartContext';
import { Toaster } from 'react-hot-toast';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><CartProvider>
        {children}
        <Toaster
  position="top-center"
  toastOptions={{
    style: {
      background: '#ffffff',
      border: '1px solid #d1fae5',
      color: '#065f46',
      padding: '12px 16px',
      fontWeight: 500,
      fontFamily: 'Poppins, sans-serif',
      boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    },
    success: {
      iconTheme: {
        primary: '#16a34a',
        secondary: '#ecfdf5',
      },
    },
    error: {
      iconTheme: {
        primary: '#dc2626',
        secondary: '#fef2f2',
      },
    },
  }}
/>

        </CartProvider>
      </body>
    </html>
  );
}
